import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styled from 'styled-components'


export default function Home() {



const [iscolor, setcolor] = useState('pink');



  return (
    <div>
      <Head>
        <title>color change</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Container style={{backgroundColor:iscolor}}>
      
      </Container>
      <Box>
        <input type="text" value={iscolor} onChange={(e)=>setcolor(e.target.value)}/>
        
      </Box>
      
      
      </div>)}

      const Box = styled.div`
       place-items:center;
      
      `;
      const Container = styled.div`
      height:300px;
      width:300px;
      
      
      
      `;


  

